[package]
name = "rust-exercise-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
fake = { version = "3.0.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.95"
rayon = "1.10"
